version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
      - REPOSITORY_URI_NGINX=245423107264.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/port-nginx-repository

  build:
    commands:
      - echo Building the Docker image...
      - docker image build -t ${REPOSITORY_URI_NGINX}:latest docker
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push ${REPOSITORY_URI_NGINX}:latest
      - echo Writing image definitions file...
      - printf "[{\"name\":\"port-nginx-container\",\"imageUri\":\"${REPOSITORY_URI_NGINX}:latest\"}]" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json